export const TITLE_TRUNCATE_LENGTH = 160;
export const CHANNEL_NAME_TRUNCATE_LENGTH = 40;

export const TRENDING_INITIAL_VIDEO_COUNT = 8;
export const MIN_TRENDING_AGE_MINUTES = 2 * 60;
export const MAX_TRENDING_AGE_MINUTES = 1.5 * 24 * 60;
export const MIN_TRENDING_VIEWS = 1000;
export const MAX_TRENDING_VIEWS = Number.POSITIVE_INFINITY;
