import Head from "next/head";

import Dashboard from "~/components/Dashboard";
import Footer from "~/components/ui/Footer";
import Header from "~/components/ui/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>learnbyvideo.dev Stats Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-3 sm:p-10">
        <Header />
        <Dashboard />
        <Footer />
      </main>
    </>
  );
}
